#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-PerformanceAnalytics
Version  : 1.5.2
Release  : 29
URL      : https://cran.r-project.org/src/contrib/PerformanceAnalytics_1.5.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/PerformanceAnalytics_1.5.2.tar.gz
Summary  : Econometric Tools for Performance and Risk Analysis
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-PerformanceAnalytics-lib = %{version}-%{release}
Requires: R-Hmisc
Requires: R-caTools
Requires: R-car
Requires: R-cli
Requires: R-gdata
Requires: R-gplots
Requires: R-gtools
Requires: R-quadprog
Requires: R-quantmod
Requires: R-quantreg
Requires: R-timeSeries
Requires: R-tseries
Requires: R-withr
Requires: R-xts
Requires: R-zoo
BuildRequires : R-Hmisc
BuildRequires : R-caTools
BuildRequires : R-car
BuildRequires : R-cli
BuildRequires : R-gdata
BuildRequires : R-gplots
BuildRequires : R-gtools
BuildRequires : R-quadprog
BuildRequires : R-quantmod
BuildRequires : R-quantreg
BuildRequires : R-timeSeries
BuildRequires : R-tseries
BuildRequires : R-withr
BuildRequires : R-xts
BuildRequires : R-zoo
BuildRequires : buildreq-R

%description
# PerformanceAnalytics: Econometric tools for performance and risk analysis.
`PerformanceAnalytics` provides an R package of econometric functions
for performance and risk analysis of financial instruments or portfolios.
This package aims to aid practitioners and researchers in using the latest research for
analysis of both normally and non-normally distributed return streams.

%package lib
Summary: lib components for the R-PerformanceAnalytics package.
Group: Libraries

%description lib
lib components for the R-PerformanceAnalytics package.


%prep
%setup -q -c -n PerformanceAnalytics

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552878898

%install
export SOURCE_DATE_EPOCH=1552878898
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library PerformanceAnalytics
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library PerformanceAnalytics
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library PerformanceAnalytics
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  PerformanceAnalytics || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/PerformanceAnalytics/DESCRIPTION
/usr/lib64/R/library/PerformanceAnalytics/INDEX
/usr/lib64/R/library/PerformanceAnalytics/Meta/Rd.rds
/usr/lib64/R/library/PerformanceAnalytics/Meta/data.rds
/usr/lib64/R/library/PerformanceAnalytics/Meta/features.rds
/usr/lib64/R/library/PerformanceAnalytics/Meta/hsearch.rds
/usr/lib64/R/library/PerformanceAnalytics/Meta/links.rds
/usr/lib64/R/library/PerformanceAnalytics/Meta/nsInfo.rds
/usr/lib64/R/library/PerformanceAnalytics/Meta/package.rds
/usr/lib64/R/library/PerformanceAnalytics/Meta/vignette.rds
/usr/lib64/R/library/PerformanceAnalytics/NAMESPACE
/usr/lib64/R/library/PerformanceAnalytics/NEWS
/usr/lib64/R/library/PerformanceAnalytics/R/PerformanceAnalytics
/usr/lib64/R/library/PerformanceAnalytics/R/PerformanceAnalytics.rdb
/usr/lib64/R/library/PerformanceAnalytics/R/PerformanceAnalytics.rdx
/usr/lib64/R/library/PerformanceAnalytics/data/edhec.csv.gz
/usr/lib64/R/library/PerformanceAnalytics/data/edhec.rda
/usr/lib64/R/library/PerformanceAnalytics/data/managers.csv.gz
/usr/lib64/R/library/PerformanceAnalytics/data/managers.rda
/usr/lib64/R/library/PerformanceAnalytics/data/portfolio_bacon.csv.gz
/usr/lib64/R/library/PerformanceAnalytics/data/portfolio_bacon.rda
/usr/lib64/R/library/PerformanceAnalytics/data/prices.rda
/usr/lib64/R/library/PerformanceAnalytics/data/weights.rda
/usr/lib64/R/library/PerformanceAnalytics/doc/EstimationComoments.R
/usr/lib64/R/library/PerformanceAnalytics/doc/EstimationComoments.Rnw
/usr/lib64/R/library/PerformanceAnalytics/doc/EstimationComoments.pdf
/usr/lib64/R/library/PerformanceAnalytics/doc/PA-Bacon.R
/usr/lib64/R/library/PerformanceAnalytics/doc/PA-Bacon.Rnw
/usr/lib64/R/library/PerformanceAnalytics/doc/PA-Bacon.pdf
/usr/lib64/R/library/PerformanceAnalytics/doc/PA-charts.R
/usr/lib64/R/library/PerformanceAnalytics/doc/PA-charts.Rnw
/usr/lib64/R/library/PerformanceAnalytics/doc/PA-charts.pdf
/usr/lib64/R/library/PerformanceAnalytics/doc/PerformanceAnalyticsChartsPresentation-Meielisalp-2007.R
/usr/lib64/R/library/PerformanceAnalytics/doc/PerformanceAnalyticsChartsPresentation-Meielisalp-2007.Rnw
/usr/lib64/R/library/PerformanceAnalytics/doc/PerformanceAnalyticsChartsPresentation-Meielisalp-2007.pdf
/usr/lib64/R/library/PerformanceAnalytics/doc/PerformanceAnalyticsPresentation-UseR-2007.R
/usr/lib64/R/library/PerformanceAnalytics/doc/PerformanceAnalyticsPresentation-UseR-2007.Rnw
/usr/lib64/R/library/PerformanceAnalytics/doc/PerformanceAnalyticsPresentation-UseR-2007.pdf
/usr/lib64/R/library/PerformanceAnalytics/doc/index.html
/usr/lib64/R/library/PerformanceAnalytics/doc/portfolio_returns.R
/usr/lib64/R/library/PerformanceAnalytics/doc/portfolio_returns.Rnw
/usr/lib64/R/library/PerformanceAnalytics/doc/portfolio_returns.pdf
/usr/lib64/R/library/PerformanceAnalytics/doc/textplotPresentation-CRUG-2011.R
/usr/lib64/R/library/PerformanceAnalytics/doc/textplotPresentation-CRUG-2011.Rnw
/usr/lib64/R/library/PerformanceAnalytics/doc/textplotPresentation-CRUG-2011.pdf
/usr/lib64/R/library/PerformanceAnalytics/help/AnIndex
/usr/lib64/R/library/PerformanceAnalytics/help/PerformanceAnalytics.rdb
/usr/lib64/R/library/PerformanceAnalytics/help/PerformanceAnalytics.rdx
/usr/lib64/R/library/PerformanceAnalytics/help/aliases.rds
/usr/lib64/R/library/PerformanceAnalytics/help/paths.rds
/usr/lib64/R/library/PerformanceAnalytics/html/00Index.html
/usr/lib64/R/library/PerformanceAnalytics/html/R.css
/usr/lib64/R/library/PerformanceAnalytics/tests/Examples/PerformanceAnalytics-Ex.Rout.save
/usr/lib64/R/library/PerformanceAnalytics/tests/testthat.R
/usr/lib64/R/library/PerformanceAnalytics/tests/testthat/test_toPeriodContributions.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/PerformanceAnalytics/libs/PerformanceAnalytics.so
/usr/lib64/R/library/PerformanceAnalytics/libs/PerformanceAnalytics.so.avx2
/usr/lib64/R/library/PerformanceAnalytics/libs/PerformanceAnalytics.so.avx512
